### ISSUE TITLE
This version of the Expo app is out of date. Uninstall the app and run again to upgrade.

### ISSUE THREAD

**Issue by Tzikas** [bkdev98/react-native-boilerplate#4]
Getting this error `This version of the Expo app is out of date. Uninstall the app and run again to upgrade.` when running on ios simulator but works fine on phone.  Not sure, how to update this.

**Comment by AndersGerner** [comment]
@Tzikas You can find upgrade notes for the latest SDK version (28) here: https://blog.expo.io/expo-sdk-v28-0-0-is-now-available-f30e8253b530

**Comment by Tzikas** [comment]
Thanks!! Is that for iOS as well?

**Comment by Tzikas** [comment]
This: https://github.com/react-community/create-react-native-app/issues/113#issuecomment-289325092 worked for me.  Simply `Shift-CMD-H`, holding down the icons to delete and then deleting the app followed by a yarn start will download a newer version of expo.

**Comment by GodJerry** [comment]
not works and idiot

**Comment by j-funk** [comment]
This works for me, thanks.

**Comment by doutorapple** [comment]
https://stackoverflow.com/questions/54251369/expo-is-out-of-date-uninstall-and-run-again-to-upgrade

**Comment by mriveros** [comment]
To resolve this issue you need uninstall and install again the Expo app in your device or simulator. This work for me.
